pipeline {

    agent any
    stages {
		stage('Checkout') {
			steps {
				checkout scm
			}			
		}
        stage('Build') {
            steps {
                sh 'docker build -t harsh1354/declarative:latest bulletin-board-app/'
                sh 'echo "Image build is complete"'
            }
        }
        stage('Tag') {
            steps {
                sh "docker tag harsh1354/declarative:latest harsh1354/declarative:${env.BUILD_ID}"
                sh 'echo "Image tag is complete"'
				sh 'docker images'
            }
        }
        stage('Push') {
            steps {
				withCredentials([usernamePassword(credentialsId: 'dockerHub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
					sh "docker login -u $USERNAME -p $PASSWORD"
					sh "docker push harsh1354/declarative:latest"
					sh "docker push harsh1354/declarative:${env.BUILD_ID}"
				}
            }
        }
    }
}
