pipeline {
    agent any
    stages {
	stage('Checkout') {
	    steps {
		checkout scm
	    }			
        }
        stage('Example Build') {
            steps {
                sh 'echo "harsh"'
                sh 'ls -l'
            }
        }
    }
}
