pipeline {
    agent any
    stages {
		stage('Checkout') {
			steps {
				checkout scm
			}			
    }
        stage('Example Build') {
            steps {
                sh 'docker build -t harsh1354/declarative:latest bulletin-board-app/'
                sh 'echo "Image build is complete"'
				sh 'docker images'
            }
        }
    }
}
